In [5]:
import numpy as np
D_array = np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
print(D_array)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
print(D_array[0,0,1])

1


In [9]:
print(D_array[1,2,1])

21


In [10]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [11]:
arr.shape


(2, 4)

In [12]:
arr.strides

(16, 4)

In [13]:
arr.ndim


2

In [14]:
arr.data

In [15]:
arr.size

8

In [17]:
arr.itemsize

4

In [21]:
arr.real

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr.base


In [22]:
arr.imag


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
import numpy as np
array = np.array([1,2,3j,5])
print(array)

[1.+0.j 2.+0.j 0.+3.j 5.+0.j]


In [10]:
arr = np.array([[1,2,3j,4],[5,6,7,8j]])
arr.T

array([[1.+0.j, 5.+0.j],
       [2.+0.j, 6.+0.j],
       [0.+3.j, 7.+0.j],
       [4.+0.j, 0.+8.j]])

In [11]:
arr.real

array([[1., 2., 0., 4.],
       [5., 6., 7., 0.]])

In [12]:
arr.nbytes

128

In [13]:
arr.imag

array([[0., 0., 3., 0.],
       [0., 0., 0., 8.]])